### ISSUE TITLE
[Help Wanted] Also Bug(?) problem report

### ISSUE THREAD

**Issue by NickInManchester** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#52] opened 2021-03-25 17:57 UTC
I've just installed SkyQ with your code in Home Assistant (Everything latest versions) and it was a clean smooth process for the main sky box. But using the HACS approach I struggled to find how to add an extra SkyQ box. Now done via my configuration.yaml file. 

`media_player:
  - platform: skyq
    name: SkyQ Rear Utility
    host: 192.168 1.31
    live_tv: true
  - platform: skyq
    name: SkyQ Our Bedroom
    host: 192.168.1.32
    live_tv: true
`

One of my extra boxes integrated cleanly (the 2nd one) with no issues but the other one has a problem which I have no idea how to resolve. Perhaps it needs me to re-install. 

> "This entity ("media_player.skyq_rear_utility") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.
> 
> You can overwrite some attributes in the entity customizations section."
> 

I've tried renaming the entity, rebooting ... with no success.

If so, a button on the options to add a new skyQ box or remove one would be a great extra feature. I currently have two entities Identified as being SkyQ the main box and one other, the integration says it knows 1 device and 1 entity even though there are now 2 of each?

Some way to re-configure without a delete all and insert would also be great. I'm currently getting for my 3rd SkyQ box which won't link. It is loaded as an unavailable media_player not a SkyQ, its spec is identical to the box that works excepting its name and IP address:

Any help resolving this would be gratefully had.

**Comment by RogerSelwyn** [comment] 2021-03-25 18:12
When you want to add an extra box, you literally just add the integration again. Do exactly the same process as you did before. No need to do via YAML. It should end up looking like this.

<img width="287" alt="Screenshot 2021-03-25 at 18 05 33" src="https://user-images.githubusercontent.com/7115783/112522062-1a8ca300-8d95-11eb-8a48-51c7018db239.png">

I suspect you are getting duplicates because you have added via UI as well as via YAML. The identifier uses serial number, so a duplicate can only be caused by adding the same device twice.

I'm sorry HA does not provide a way to change the main identifier for a device (i.e. IP address) via the standard UI. If you don't like the inflexibility of the UI, just delete them all from there and add via YAML. Use one or the other not both.

HACS is only an install mechanism for the code, it is not a configuration mechanism. You can use HACS to install, and upgrade, and configure by UI or YAML as you like.

**Comment by NickInManchester** [comment] 2021-03-25 19:12
Thanks. I'll try that later. Can you add a line to the documentation saying
this. It did not occur to me!

Nick

**Comment by RogerSelwyn** [comment] 2021-03-25 19:47
I will do when you confirm this solves your problems.

**Comment by RogerSelwyn** [comment] 2021-03-25 21:38
Didn't mean to close it.

**Comment by RogerSelwyn** [comment] 2021-03-26 07:34
Added an extra line to documentation - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/commit/3c8e8ea0ecb5e41d084dcf52e379f1d6a4a99c4b

**Comment by NickInManchester** [comment] 2021-03-26 09:49
Yes, problems solved, see process below.

One new feature request to make life easier - ability to copy/duplicate set
of selected channels between the entity setups. This is what took me the
largest amount of time, they are all the same in my case with some minor
differences in radio/news channels.

Thanks for the fast given helpful advice! Great integration we'll use
frequently 🙂

My process:

Removed all references to the skyq entities to be got rid of in my config
files.

Rebooted

Removed same entities from HA's entity list in config dashboard.

Rebooted

Added new Skyq integrations for each mini box. Did the options - channel
choices.

Made it visible in my lovelace config.

Tested - all working as expected.

Regards

Nick

**Comment by RogerSelwyn** [comment] 2021-03-26 10:12
Thanks. I'll consider the option for duplication of config and whether it is achievable via the UI.

**Closed by RogerSelwyn** 2021-03-26 10:12 UTC
Labels: help wanted
