### ISSUE TITLE
Add support for channel alias for friendly_name entries in switches.YAML [Feature Request]

### ISSUE THREAD

**Issue by ChrisHammond56** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#33] opened 2020-10-19 15:07 UTC
I have, in the past month or so, started to integrate with Alexa. The underlying integration seems to be working fine. I wonder if you have considered adding an alias for some of the friendly channel names entries in the switch.yaml that is created. You see, at the moment, I can ask Alexa to ‘switch on BBC One HD in the Lounge’ and that is fine, however, attempting to ‘switch on Sky Sports Premier League HD’ does not work (mostly), as the friendly name is ‘SkySp PL HD in the Lounge’ . I know this is replicating the channel name from the SkyQ box, so its not a criticism of the plugin. Am currently ‘fixing up’ the yaml after the file has been created. This is currently calling a BASH script via a service entry in HA that is triggered manually (although I could create an ‘on HA startup event’ that could automate that phase. But I was wondering if that is do-able with the integration?

**Comment by RogerSelwyn** [comment] 2020-10-19 17:25
Have you considered using ‘Custom Source’? You can name them as you like, you just need to specify the commands you want to send (e.g. 3,0,1).

**Comment by ChrisHammond56** [comment] 2020-10-20 14:20
I had. But I am all for utilising what is already there. The plugin already has the channels that I can select from the list in the GUI. I would need to get the list of Alias channels, and then add those via the Custom Service, and omit from the GUI tick boxes. It's doable, don't get me wrong, but I prefer the GUI click and set approach. The attached amended python file 
[config_gen.py.zip](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/5409290/config_gen.py.zip)

may be a solution, in that one could just define the alias file, and the switches are generated correctly, without having to alter the GUI.

I have also amended the attached file to fixup the error generated when E! or E! HD has been selected from the GUI as a mapped channel.

**Comment by RogerSelwyn** [comment] 2020-10-20 14:56
Let me chew on it some more. I'd rather have something that can be done entirely through the UI, rather than having to edit a file in the file system. A way maybe to add another JSON structured field similar to custom sources which allows the alias pairs to be added.

**Comment by RogerSelwyn** [comment] 2020-10-22 07:43
@ChrisHammond56 - how many alias pairs are you looking for? Just trying to judge whether adding an extra json field is reasonable. The problem is I can this being a reasonably common use case (I know others are using Custom Sources to achieve the same goal), so I don't really want to have people having to add files into the file system.

**Comment by ChrisHammond56** [comment] 2020-10-28 09:50
Hi Roger. Sorry for the delay, I have been seriously busy with work and didn’t have time to check this for you. I currently have 42 channel aliases. Some of those are duplicates due to +1 channels.

 

Regards,

Chris

**Comment by RogerSelwyn** [comment] 2021-01-20 13:20
@ChrisHammond56, I'm just taking a look at this request. I think it is something where I can just provide the capability in the code if someone places a file in the right place. Would you be up for updating your solution to use a json file format, and apply your changes to the current version of config_gen.py (I've applied a fix recently)?

**Comment by RogerSelwyn** [comment] 2021-02-16 16:07
No response, so closing the request.

**Comment by ChrisHammond56** [comment] 2021-02-27 20:40
Roger. My apologies. I have had a very tight work project which is now complete, and it was remis of me to not at lease acknowledge your update. Can this be reopened and what would you like me to do?

 

Thanks

Chris

**Comment by RogerSelwyn** [comment] 2021-02-27 20:51
Hi Chris, happy to re-open. If you can re-apply your changes to the current set of code, and ideally have the lookup be in json format, I can look to incorporate. You may have noticed that I have moved config_gen into the classes folder and called it switchmaker. If you can't do the json handling, no worries I can do it.

**Comment by ChrisHammond56** [comment] 2021-02-28 23:42
Hi Roger. I hadn’t even upgraded to the latest (still at 2.4.4) as I had work commitments. I am not a JSON man 😊. If you could integrate the JSON stuff, that would be great. If you need anything from me, just let me know.

 

I will upgrade to the latest over the next day or so, and send you my modified code if that is of any use?

 

Regards

Chris

**Comment by ChrisHammond56** [comment] 2021-03-01 00:20
HI Roger. Here is the modified switchmaker.py file (and an example alias file).

 

Chris

 

 

From: chrishammond@peakprod.co.uk <chrishammond@peakprod.co.uk> 
Sent: 28 February 2021 23:42
To: 'RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer' <reply@reply.github.com>; 'RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer' <Home_Assistant_SkyQ_MediaPlayer@noreply.github.com>
Cc: 'ChrisHammond56' <chris@peakprod.co.uk>; 'Mention' <mention@noreply.github.com>
Subject: RE: [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer] Add support for channel alias for friendly_name entries in switches.YAML [Feature Request] (#33)

 

Hi Roger. I hadn’t even upgraded to the latest (still at 2.4.4) as I had work commitments. I am not a JSON man 😊. If you could integrate the JSON stuff, that would be great. If you need anything from me, just let me know.

 

I will upgrade to the latest over the next day or so, and send you my modified code if that is of any use?

 

Regards

Chris

**Comment by RogerSelwyn** [comment] 2021-03-01 11:27
Hi Chris - because you emailed a response it didn't attach your files to the thread on Github. Can you comment directly on GitHub and add your attachments.

**Comment by ChrisHammond56** [comment] 2021-03-01 16:59
There you go. Sorry about that.

[skyqChannels.zip](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/files/6063169/skyqChannels.zip)

**Comment by RogerSelwyn** [comment] 2021-03-01 17:04
Thanks :-)

**Comment by RogerSelwyn** [comment] 2021-03-02 09:03
Please can you have a look at v2.5.4. Note the file is in yaml format and called `skyqswitchalias.yaml`. Just replace your commas with colon space and rename file. This will also allow you to rename any switch name, so you can change 'pause' to 'halt' if you wish.

**Comment by ChrisHammond56** [comment] 2021-03-02 20:29
Ok. looking promising. It's essentially working 👍 I have defined the alias's and they have been applied. I have 2 issues, but I think they are more fundamental. As mentioned previously, when a channel has an ! in it, E! for example, the plugin does not replace it, and the HA config check fails in the skyq<location>/yaml. This is a simple fix in the switchmaker.py I think?

I have one other issue, and I haven't had time to track it down. I am attempting to use an alias for friendly_name: 'SkySp F'ball HD'. As the YAML for the alias cannot have an apostrophe (') in it, I have defined the alias as:

SkySp Fball HD: Sky Sports Football HD

However, the skyq<location>/yaml created has not mapped the alias, and instead inserted the normal friendly_name. This is confusng, as switchmaker.py explicitely maps "**_'_**" to "", so the friendly_name should be SkySp Fball HD.

On the positive side, if I deselect SkySp F'ball HD and E! from the list in the integration list, the latest 2.5.4 is working fine.

Let me know if you need anything from me.

**Comment by RogerSelwyn** [comment] 2021-03-02 20:43
Ok, I’ll try to fix those over the next couple of days.

**Comment by RogerSelwyn** [comment] 2021-03-03 09:09
Hi Chris - looking at these. For your football issue, in the alias file just put ' in, it is removing it from the switch name not the friendly_name. That said, I found another issue in that removing the quote means when you try to trigger the switch it doesn't work because it doesn't match to any source. So when you do the next update, you will find it is now escaped as two x '. I've tested and this works.

I've also changed it to handle ! and /.

**Comment by RogerSelwyn** [comment] 2021-03-03 09:16
New release - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.5

**Comment by ChrisHammond56** [comment] 2021-03-04 14:14
Cool. That's working perfect now with that v2.5.5 release. Donation on it's way..

**Comment by RogerSelwyn** [comment] 2021-03-04 14:20
OK, I'll release and thank you

**Comment by ChrisHammond56** [comment] 2021-03-04 17:07
I spoke too soon. Just rebooted my HASS, and got this:

Invalid config for [switch.template]: invalid slug **_skyq_e!hdoffice_** (try skyq_e_hdoffice) for dictionary value @ data['switches']. Got OrderedDict([('skyq_pauseoffice', OrderedDict([('value_template', '{{"off"}}'), ('friendly_name', 'pause in the Office'), ('turn_on', OrderedDict([('service', 'media_player.media_pause'), ('data', OrderedDict([('entity_id', 'media_player.office_sky_q_mini')]))])), ('turn_off', OrderedDict([('service', 'script.placeholder')]))])), ('skyq_playoffice', OrderedDict([('value_template', '{{"off"}}'), ('friendly_name', 'play in the Office'), ('turn_on', OrderedDict([('service', 'media_player.media_p.... (See ?, line ?).

Also, switch created with this in the YAML
    skyq_e!hdoffice:
      value_template: '{{"off"}}'
      friendly_name: 'E HD in the Office'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.office_sky_q_mini
          source: 'E! HD'

I have an alias for this channel E! HD: E HD, so looks like the friendly_name was applied.

**Comment by RogerSelwyn** [comment] 2021-03-04 17:30
"E!" should get changed to "E". I just remove the ! (line 57 of switchmaker). My room name (for testing) is skyq, so I get 'skyq_ehdskyq' without doing any aliasing. When I add the alias, I get the below.

```
    skyq_ehdskyq:
      value_template: '{{"off"}}'
      friendly_name: 'E HD in the skyq'
      turn_on:
        service: media_player.select_source
        data:
          entity_id: media_player.sky_q
          source: 'E! HD'
      turn_off:
        service: script.placeholder
```

Bear in mind the switches don't get generated until after HA has started, so it usually takes another boot to get them in play. I'd probably delete the switch file (you'd need to comment it out of config.yaml), then reboot (and and back to config.yaml) and reboot again to get it in play. If that is still generating wrong, then I'll need to think deeper as to how it isn't removing the !.

**Comment by ChrisHammond56** [comment] 2021-03-17 00:06
Yep that fixed it. I went through the steps you provided (delete and reboot Etc) and the channels are now mapped/aliased correctly. Excellent job.

**Comment by RogerSelwyn** [comment] 2021-03-17 10:34
Fixed with - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.5.6

**Closed by RogerSelwyn** 2021-03-17 10:34 UTC
Labels: Feature Request
