### ISSUE TITLE
[Feature Request] order of channels / sources 

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer#8] opened 2020-05-26 19:28 UTC
**Is your feature request related to a problem? Please describe.**
Can you control the order that sources appear. 
My channels appear alphabetically. 
I would prefer they appear numerically. 
Or ideally in the order I enter them. 

Is it possible ?

**Comment by RogerSelwyn** [comment] 2020-05-26 19:35
Are you doing source config via yaml or via the config_flow in alpha release?

**Comment by B-Hartley** [comment] 2020-05-26 19:37
I’m using the config flow.

**Comment by RogerSelwyn** [comment] 2020-05-26 19:51
I assume you mean in the custom sources option then :-). Can you give me the Json you have entered, and I'll see what I can do. I can see the channel sources aren't in channel order, which they should be, so I'll sort that as well.

**Comment by RogerSelwyn** [comment] 2020-05-26 21:03
I've just been doing some work on this. I can see that channels were getting shown in the order they were added (i.e. if I selected 106 & 107 the first time around, then went back to options and add 102, they would show as 106, 107, 102 without the channel numbers of course). This doesn't make sense and is counter to anything normal. 

So currently I have changed it to order by channel number with radio stations last (which is a pain since their channel numbers start with 0).

However, custom sources seem to show in the order they are entered in the JSON. So the following:

> {"Netflix": "1,2,3", "Other": "4,5,6", "Another","7,8,9"}

Shows as - Netflix, Other, Another - in the sources list, which seems to make sense.

The final item is that currently custom sources appear before channel sources.

So, choices that could be made, I've **highlighted** current design:

- The sort order for channels, alphabetic or **numerical**. 
- The sort order for custom sources, alphabetic by name, alphabetic by value, **as-is**.
- The order of the two types of sources, **custom first** or channels first.

I could of course make all this configureable, but to be honest if people are that worried they can create a massive JSON structure and put it in custom sources, or just use YAML. So I don't want to add loads and loads of options, it just makes a mess and adds code complexity.

**Comment by B-Hartley** [comment] 2020-05-27 08:38
I'll take a look later.
At first glance I believe I entered the JSON as:
{"BBC1": "1", "BBC2": "2", "ITV": "3", "Ch4": "4", "Ch5": "5",  "Sky1": "6", "Four7": "7", "Fox": "8","Dave": "9"}

But when I look now, it says......
{"BBC1": "1", "BBC2": "2", "Ch4": "4", "Ch5": "5", "Dave": "9", "Four7": "7", "Fox": "8", "ITV": "3", "Sky1": "6"}

In fact, I just changed it back and it changed itself to alphabetic.

Personally I think it would be most useable if ticking channels added them in the order you added them.  (I think the current behaviour).
And custom channels displayed in the order you typed them in.

Custom first.


Equally channels numeric, custom source numeric, would work fine for my use case.

Thanks.

**Comment by RogerSelwyn** [comment] 2020-05-27 09:09
Strange, I thought I checked last night that the custom sources don't get sorted, and I've just checked again and they do (I haven't added a sort, so no idea why that happens), so I'll fix that.

I'll revert the change on sorting channels (but leave the code there) and see what screams I get from the community when it starts getting used.

**Comment by B-Hartley** [comment] 2020-05-27 09:21
Thanks.  Do you have any plans to try and get this into Home Assistant core as an official plugin? or are there too many hoops to jump?

**Comment by RogerSelwyn** [comment] 2020-05-27 09:25
I've been working towards getting to a standard which would allow incorporation as an official plugin, and I think I'm party much there (config_flow was a major element). What worries me is that Sky Q api is completely undocumented (officially). There are people who have figured it out by sniffing traffic/etc. And I've got a reasonable understanding by looking at the data a lot as part of the work I have done. So whilst it works now, who knows if it will work in 6 months time, and with more people using it there could be a lot of pressure to fix something that can't be fixed without breaking Sky Ts & Cs and reverse engineering their code.

**Comment by RogerSelwyn** [comment] 2020-05-27 11:54
This commit should retain the input channel/custom source ordering. It will break existing custom source configs. Since this is alpha code, please just re-input your custom source config as needed.

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/commit/e2634fe8c7e4e63b8f51cf84392bc498f638bdfb

**Comment by B-Hartley** [comment] 2020-05-27 12:23
Custom sources seemed to stick.
When I installed it, it had dummy data in the custom source field.  (test data?)

Regarding the official plugin thing, I understand what you are saying.  I guess you would just have to be crystal clear of the ground rules that you'll do your best.  and see what happens ??

I for one really appreciate the work you've done.  I have on my list to get my Python to a level where I can actually help with this kind of stuff.

**Comment by RogerSelwyn** [comment] 2020-05-27 13:05
Umm, there shouldn't be any dummy data in Alpha 6. Maybe it is interpreting old data you have saved. The problem is I was saving a Python Dict (which was getting sorted by HA), and the HA doesn't support saving an OrderedDict (which should guarantee the order), so I have changed it to a Python List which retains it's order. When you have done some Python you will see this fairly early on in any course you do :-)

Just re-input and go forward...

**Comment by B-Hartley** [comment] 2020-05-30 11:17
I don't seem to be able to change source on SkyQ.
I've tried through the lovelace front end, and also by making a direct service call to media_player.select_source

I'm getting this in log...

Log Details (ERROR)
Logger: pyskyqremote.skyq_remote
Source: util/thread.py:20
First occurred: 12:11:28 PM (18 occurrences)
Last logged: 12:15:38 PM

E0010 - Invalid command: 192.168.21.170 : 138
E0010 - Invalid command: 192.168.21.170 : 105
E0010 - Invalid command: 192.168.21.170 : 106
E0010 - Invalid command: 192.168.21.170 : 115
E0010 - Invalid command: 192.168.21.170 : 124

**Comment by RogerSelwyn** [comment] 2020-05-30 12:57
- How have you configured the entity? Config_flow or YAML? 
- What type of source is it if via config_flow, channel or custom?
- Please provide details of the source configuration for YAML or custom. i.e. what is the YAML entry, or what do you have as JSON in the custom source option?

**Comment by RogerSelwyn** [comment] 2020-05-30 14:05
Just in case you have put invalid commands in the custom source JSON, I am adding extra validation into the config_flow to ensure only valid commands are included.

**Comment by B-Hartley** [comment] 2020-05-30 15:24
Hi,  the Json for custom sources is...
{"BBC1": "115", "BBC2": "102", "ITV": "103", "Ch4": "138", "Ch5": "105", "Sky1": "106", "Four7": "7", "Fox": "124", "Dave": "111"}

I tried removing the integration and re-adding it.  Then adding the custom json again.

**Comment by RogerSelwyn** [comment] 2020-05-30 15:30
I can immediately see those are invalid. Valid numerical values are 0,1,2,3,..... 115 is not one of those :-) You need to put "1,1,5". Bear in mind, the commands can also take 'home', 'red', etc. So they mimic the buttons on the remote, and there is no 115 button on the remote.

**Comment by RogerSelwyn** [comment] 2020-05-30 15:31
You could also achieve that by selecting the channels in the same order in the channel drop down.

**Comment by B-Hartley** [comment] 2020-05-30 15:34
Thanks.  I've only used single digits in there before as I was acessing favourites, but it occurred to me that it is actually faster to go to channel 115 than it is to go to channel 1 as it doesn't have to wait for more potential input.  Apologies for my "user error", I'll just call it validation testing !

I realise I could choose them from the list, but I prefer the short titles of "BBC1" rather than "BBC 1 HD" or whatever.   Thanks for the quick response.

**Comment by B-Hartley** [comment] 2020-05-30 15:35
btw.  I've noticed that you have "netflix" types sources that you use with a combination of "home","down","down" etc.  Does it work reliably?  does the home key always take you into the menu at the same point, or are you relying on it being left in a certain state. ?

**Comment by RogerSelwyn** [comment] 2020-05-30 15:40
No idea. I have them copied from previous people's YAML. I never use these sources myself, but I enjoy making it work for others. There is no reason they shouldn't work as long as they don't move around on the Sky Q screens. Commands are sent to the box 0.5 seconds apart. That was how it was setup when I took it on, no-one has complained that I've seen.

**Comment by RogerSelwyn** [comment] 2020-05-30 15:41
> Thanks. I've only used single digits in there before as I was acessing favourites, but it occurred to me that it is actually faster to go to channel 115 than it is to go to channel 1 as it doesn't have to wait for more potential input. Apologies for my "user error", I'll just call it validation testing !
> 
> I realise I could choose them from the list, but I prefer the short titles of "BBC1" rather than "BBC 1 HD" or whatever. Thanks for the quick response.

No worries, as I've said, I've added some validation at config time, to stop these errors being generated later. It will be in the next beta.

**Comment by RogerSelwyn** [comment] 2020-06-02 14:24
Fixed by - [v2.2.0](https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.2.0)

**Closed by RogerSelwyn** 2020-06-02 14:24 UTC
Labels: Feature Request
